### ISSUE TITLE
First basic working version of visur

### ISSUE THREAD

**Issue by jgolden5** [jeremygurr/visur#94]
- [x] Data Classes #76 
- [x] Quantum Movement #86 #87 
- [x] Quantum Start/End #89 
- [x] Span Movement (for spans 0-1) #90 
- [x] Insert Mode #91 
- [x] Replace Mode #43 
- [x] Deleting #69 
- [x] Searching #93 
- [x] Refactor VirtualDC #105 
- [x] Redo vertical movement for character and line quantums #106 
- [x] Scrolling #67
- [x] Fix visuals in visur.js #104 
- [x] Make sure I understand it all
